service: aws-node-rest-api

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  getTodos:
    handler: handler.getTodos
    events:
      - http:
          path: /todos
          method: get
  getTodo:
    handler: handler.getTodo
    events:
      - http:
          path: /todos/{id}
          method: get
